### ISSUE TITLE
Fails to run on Windows runners: Invalid credentials specified

### ISSUE THREAD

**Issue by SanderVocke** [egor-tensin/setup-clang#19]
Since just now, trying to invoke this action from Github Actions' Windows runner fails:

```
Run egor-tensin/setup-clang@v1
  with:
    version: latest
    platform: x64
    cygwin: 0
    cc: 1
    hardlinks: 0
  env:
    BUILD_TYPE: Release
    PIP_BREAK_SYSTEM_PACKAGES: 1
    pythonLocation: C:\hostedtoolcache\windows\Python\3.8.10\x64
    PKG_CONFIG_PATH: C:\hostedtoolcache\windows\Python\3.8.10\x64/lib/pkgconfig
    Python_ROOT_DIR: C:\hostedtoolcache\windows\Python\3.8.10\x64
    Python2_ROOT_DIR: C:\hostedtoolcache\windows\Python\3.8.10\x64
    Python3_ROOT_DIR: C:\hostedtoolcache\windows\Python\3.8.10\x64
Run New-Variable os -Value 'Windows' -Option Constant
  New-Variable os -Value 'Windows' -Option Constant
  
  New-Variable linux_host -Value ($os -eq 'Linux') -Option Constant
  New-Variable cygwin_host -Value ('0' -eq '1') -Option Constant
  New-Variable windows_host -Value ($os -eq 'Windows' -and !$cygwin_host) -Option Constant
  
  New-Variable version -Value ('latest') -Option Constant
  New-Variable latest -Value ($version -eq 'latest') -Option Constant
  New-Variable x64 -Value ('x64' -eq 'x64') -Option Constant
  
  function Locate-Choco {
      $path = Get-Command 'choco' -ErrorAction SilentlyContinue
  '@
      }
  
      # IDK why, but without libiconv-devel, even a "Hello, world!"
      # C++ app cannot be compiled as of December 2020. Also, libstdc++
      # is required; it's simpler to install gcc-g++ for all the
      # dependencies.
      Install-Package clang gcc-g++ libiconv-devel llvm
  } elseif ($windows_host) {
      Install-Package llvm
  
      $bin_dir = Join-Path $env:ProgramFiles LLVM bin
      echo $bin_dir >> $env:GITHUB_PATH
  } else {
      throw "Sorry, installing Clang is unsupported on $os"
  }
  
  echo "clang=$clang"     >> $env:GITHUB_OUTPUT
  echo "clangxx=$clangxx" >> $env:GITHUB_OUTPUT
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
  env:
    BUILD_TYPE: Release
    PIP_BREAK_SYSTEM_PACKAGES: 1
    pythonLocation: C:\hostedtoolcache\windows\Python\3.8.10\x64
    PKG_CONFIG_PATH: C:\hostedtoolcache\windows\Python\3.8.10\x64/lib/pkgconfig
    Python_ROOT_DIR: C:\hostedtoolcache\windows\Python\3.8.10\x64
    Python2_ROOT_DIR: C:\hostedtoolcache\windows\Python\3.8.10\x64
    Python3_ROOT_DIR: C:\hostedtoolcache\windows\Python\3.8.10\x64
Chocolatey v2.2.2
Upgrading the following packages:
llvm
By upgrading, you accept licenses for the packages.
Invalid credentials specified.
Please provide credentials for: https://community.chocolatey.org/api/v2/
User name: Password: Chocolatey had an error on fv-az1105-743 (with user runneradmin):
System.InvalidOperationException: Cannot read keys when either application does not have a console or when console input has been redirected from a file. Try Console.Read.
   at System.Console.ReadKey(Boolean intercept)
   at chocolatey.infrastructure.commandline.ReadKeyTimeout.ConsoleReadKey()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Unhandled Exception: System.InvalidOperationException: Cannot read keys when either application does not have a console or when console input has been redirected from a file. Try Console.Read.
   at System.Console.ReadKey(Boolean intercept)
   at chocolatey.infrastructure.commandline.ReadKeyTimeout.ConsoleReadKey()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
Error: Process completed with exit code 1.
```

It seems to be some kind of authentication issue with Chocolatey. I don't know if it is an intermittent error or something that needs to be addressed.

**Comment by SanderVocke** [comment]
Hmm, I see the Choco community website is also down. Maybe this is just a Chocolatey availability issue.

**Comment by SanderVocke** [comment]
![image](https://github.com/egor-tensin/setup-clang/assets/11209121/437c937a-74f3-4934-b0c4-10df04393cef)

**Comment by SanderVocke** [comment]
Yes, this was a Chocolatey accessibility issue. Working again.
